# Generated by Django 5.2.1 on 2025-07-23 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='circuit',
            options={'verbose_name': 'Circuit', 'verbose_name_plural': 'Circuits'},
        ),
        migrations.AlterModelOptions(
            name='communications',
            options={'verbose_name': 'Communication', 'verbose_name_plural': 'Communications'},
        ),
        migrations.AlterModelOptions(
            name='delegates',
            options={'verbose_name': 'Delegate', 'verbose_name_plural': 'Delegates'},
        ),
        migrations.AlterModelOptions(
            name='diocese',
            options={'verbose_name': 'Diocese', 'verbose_name_plural': 'Dioceses'},
        ),
        migrations.AlterModelOptions(
            name='donations',
            options={'verbose_name': 'Donation', 'verbose_name_plural': 'Donations'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='fellowship',
            options={'verbose_name': 'Fellowship', 'verbose_name_plural': 'Fellowships'},
        ),
        migrations.AlterModelOptions(
            name='financialtransactions',
            options={'verbose_name': 'Financial Transaction', 'verbose_name_plural': 'Financial Transactions'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.AlterModelOptions(
            name='ministerialvisits',
            options={'verbose_name': 'Ministerial Visit', 'verbose_name_plural': 'Ministerial Visits'},
        ),
        migrations.AlterModelOptions(
            name='prayerrequest',
            options={'verbose_name': 'Prayer Request', 'verbose_name_plural': 'Prayer Requests'},
        ),
        migrations.AlterModelOptions(
            name='volunteerassignments',
            options={'verbose_name': 'Volunteer Assignment', 'verbose_name_plural': 'Volunteer Assignments'},
        ),
    ]
